kulashare_message:
    resource: |
        alias: kulashare.message
        except: ['delete', 'update']
        templates: KulashareMessageBundle:Default
    type: sylius.resource
#    prefix: /dashboard

kulashare_message_index:
    path: /inbox
    methods: [GET]
    defaults:
        _controller: kulashare.controller.message:indexAction
        _sylius:
            template:  KulashareMessageBundle:Default:list.html.twig
            repository:
                method:    findMessagesByUser
                arguments: ['expr:service("security.context").getToken().getUser().getId()']
            paginate:  false
            limit: 30
#            sortable:  true
            permission: true
#            sorting:
#                createdAt: desc
#
kulashare_message_create:
    path: /message/new
    methods: [GET, POST]
    defaults:
        _controller: kulashare.controller.message:createAction
        _sylius:
            form: Kulashare\Bundle\MessageBundle\Form\MessageType
            permission: true
            redirect: kulashare_message_show
            template: KulashareMessageBundle:Default:create.html.twig

kulashare_message_delete:
    path: /message/{id}
    methods: [DELETE, GET]
    defaults:
        _controller: kulashare.controller.message:deleteAction
        _sylius:
            permission: true
            redirect:
                route: kulashare_message_inbox
