kulashare_message:
    resource: "@KulashareMessageBundle/Resources/config/routing.yml"
    prefix:   /
# kulashare_frontend:
#     resource: "@KulashareFrontendBundle/Resources/config/routing.yml"
#     prefix:   /

kulashare_rental:
    resource: "@KulashareRentalBundle/Resources/config/routing.yml"
    prefix:   /

kulashare_store_front:
    resource: "@KulashareStoreFrontBundle/Resources/config/routing.yml"
    prefix:   /


kulashare_product:
    resource: "@KulashareProductBundle/Resources/config/routing.yml"
    prefix:   /

kulashare_customer:
    resource: "@KulashareCustomerBundle/Resources/config/routing.yml"
    prefix:   /

#sylius_installer:
#    resource: "@SyliusInstallerBundle/Resources/config/routing.yml"

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login

# amazon_login:
#     path: /login/check-amazon

facebook_login:
    path: /login/check-facebook

# google_login:
#     path: /login/check-google

symfony_cmf:
    resource: @CmfCreateBundle/Resources/config/routing/rest_no_locale.xml