kulashare_product_list:
    path:     /products/list
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template:  KulashareProductBundle:Default:list.html.twig
            paginate: 5
            criteria:
                userCreated: ['expr:service("security.context").getToken().getUser().getId()']
            sortable: true
            sorting:
                createdAt: desc

kulashare_product_taxon:
    path:     /products/category/{taxon}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template:  KulashareProductBundle:Default:list.html.twig
            paginate: 5
            criteria:
                mainTaxon: $taxon
            sortable: true
            sorting:
                createdAt: desc

kulashare_product:
    resource: |
        alias: sylius.product
        templates: KulashareProductBundle:Default
    type: sylius.resource

kulashare_product_preview:
    path:     /products/preview
    defaults: { _controller: KulashareProductBundle:Product:showPreview }
#kulashare_product_filter_category:
#    path:     /products/category/{categoryId}
#    defaults: { _controller: KulashareProductBundle:Product:filterProductByCategory }

kulashare_product_search:
    path:     /products-search/
    methods:  [GET]
    defaults: { _controller: KulashareProductBundle:Product:productSearch }

#kulashare_product_filter:
#    path:     /products-filter/
#    methods:  [GET]
#    defaults: { _controller: KulashareProductBundle:Product:filterProduct }
#kulashare_product_lender:
#    path:     /listing-product/
#    methods:  [GET]
#    defaults: { _controller: KulashareProductBundle:Product:productSearchbyLender }